# backend/docs/auth.yaml

openapi: 3.0.3
info:
  title: API Gestion Associative - Authentification
  version: 1.0.0
  description: Module d'authentification de l'API

servers:
  - url: http://localhost:3001/api
    description: Serveur de développement

tags:
  - name: Auth
    description: Endpoints d'authentification

paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Inscription d'un nouveau membre
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        201:
          description: Inscription réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        400:
          description: Erreur de validation
        409:
          description: Email déjà utilisé

  /auth/login:
    post:
      tags: [Auth]
      summary: Connexion d'un membre
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        200:
          description: Connexion réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        401:
          description: Identifiants invalides

  /auth/me:
    get:
      tags: [Auth]
      summary: Profil de l'utilisateur connecté
      security:
        - bearerAuth: []
      responses:
        200:
          description: Profil récupéré
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileResponse"
        401:
          description: Non authentifié

  /auth/forgot-password:
    post:
      tags: [Auth]
      summary: Demande de réinitialisation du mot de passe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        200:
          description: Email envoyé (si l'adresse existe)

  /auth/reset-password:
    post:
      tags: [Auth]
      summary: Réinitialisation du mot de passe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPasswordRequest"
      responses:
        200:
          description: Mot de passe modifié
        400:
          description: Token invalide ou expiré

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required: [nom, prenom, email, motDePasse]
      properties:
        nom:
          type: string
          minLength: 2
          maxLength: 100
          example: Dupont
        prenom:
          type: string
          minLength: 2
          maxLength: 100
          example: Marie
        email:
          type: string
          format: email
          example: marie.dupont@email.fr
        telephone:
          type: string
          example: "0612345678"
        motDePasse:
          type: string
          minLength: 8
          example: Password123!

    LoginRequest:
      type: object
      required: [email, motDePasse]
      properties:
        email:
          type: string
          format: email
        motDePasse:
          type: string

    AuthResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          properties:
            membre:
              $ref: "#/components/schemas/Membre"
            token:
              type: string
            refreshToken:
              type: string

    Membre:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nom:
          type: string
        prenom:
          type: string
        email:
          type: string
        telephone:
          type: string
        role:
          type: string
          enum: [ADMIN, MEMBRE]
        statut:
          type: string
          enum: [ACTIF, INACTIF, BUREAU]
        dateCreation:
          type: string
          format: date-time

    ResetPasswordRequest:
      type: object
      required: [token, motDePasse, confirmMotDePasse]
      properties:
        token:
          type: string
        motDePasse:
          type: string
          minLength: 8
        confirmMotDePasse:
          type: string

    ProfileResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: "#/components/schemas/Membre"
